language: rust
rust:
  - stable
  - beta
cache: cargo
before_install: nvm install 10
script: cargo test && ./build.sh

env: RUST_BACKTRACE=1
notifications:
  - email: false
branches:
  only:
  - master