language: rust
cache: cargo
matrix:
  include:
    - rust: stable
      install: true
      script:
        - cargo test --manifest-path crates/server/Cargo.toml
        - cargo test --manifest-path crates/shared/Cargo.toml
    - rust: beta
      install: true
      script:
        - cargo test --manifest-path crates/server/Cargo.toml
        - cargo test --manifest-path crates/shared/Cargo.toml
    - rust: nightly
      install: true
      before_install:
        - rustup target add wasm32-unknown-unknown
        - nvm install 10
      before_script: cargo install wasm-bindgen-cli
      script:
        - cargo test --manifest-path crates/browser/Cargo.toml
        - build.sh

env: RUST_BACKTRACE=1
notifications:
  - email: false
branches:
  only:
  - master