@echo off
echo cleaning up any existing .wasm files in the dist folder
del %~dp0dist\*.wasm
echo building the browser project
cd crates\browser
cargo +nightly build -q --target wasm32-unknown-unknown
cd ..\..
echo running wasm-bindgen against our project
wasm-bindgen ./target\wasm32-unknown-unknown\debug\wasm_tutorial_browser.wasm --browser --out-dir ./dist
echo making sure that the wasm-bindgen-chrome-hack exists
if not exist %~dp0wbch.exe (
    echo "Cloning wbch into temp directory"
    git clone https://github.com/freemasen/wasm-chrome-hack %TEMP%\wasm_tut
    cd "%TEMP%\wasm_tut"
    echo "building the chrome hack project"
    cargo build -q --release
    cd %~dp0
    echo "Attempting to copy the result"
    robocopy %TEMP%\wasm_tut\target\release %~dp0 wbch.exe
    echo "Removing temp directory for repo"
    rmdir /S /Q %TEMP%\wasm_tut
)
echo renaming the .wasm file generated by wasm-bindgen
rename %~dp0dist\wasm_tutorial_browser_bg.wasm bincode_parse.wasm
echo running the chrome hack exe
wbch.exe ./dist/wasm_tutorial_browser.js ./ts/wasm_tutorial_browser.js /bincode_parse.wasm
echo deleting the wasm-bindgen generated .js file
del /F /Q %~dp0dist\*.js
echo running webpack
%~dp0node_modules\.bin\webpack.cmd %1