#! /bin/bash
echo "Installing nightly"
~/.cargo/bin/rustup install nightly
echo "Installing wasm32-unknown-unknown"
~/.cargo/bin/rustup target add --toolchain nightly wasm32-unknown-unknown
cd ./crates/browser
echo "building the browser project"
~/.cargo/bin/cargo +nightly build --target wasm32-unknown-unknown
cd ../..
echo "installing wasm-bindgen"
~/.cargo/bin/cargo install wasm-bindgen-cli
echo "running wasm-bindgen against our project"
~/.cargo/bin/wasm-bindgen ./target/wasm32-unknown-unknown/debug/wasm_tutorial_browser.wasm --browser --out-dir ./dist
cd ./dist
ls
cd ..
echo "making sure that the wasm-bindgen-chrome-hack exists"
if [ ! -f ~/.cargo/bin/wbch ]; then
    ~/.cargo/bin/cargo install --git https://github.com/freemasen/wasm-chrome-hack --force
fi
cargo install rsass --features commandline
echo "renaming the .wasm file generated by wasm-bindgen"
NAME=bincode_parse.wasm
mv ./dist/wasm_tutorial_browser_bg.wasm ./dist/$NAME
echo "running the chrome hack bin"
~/.cargo/bin/wbch ./dist/wasm_tutorial_browser.js ./ts/wasm_tutorial_browser.js /$NAME
echo "deleting the wasm-bindgen generated .js file"
rm ./dist/*.js
echo "downloading deps"
npm install
echo "running sass"
rsass --style compressed -o ./sass/main.scss > dist/css/main.css
echo "running webpack"
./node_modules/.bin/webpack $1
