[package]
name = "wasm_tutorial_browser"
version = "0.1.0"
authors = ["robert masen <r@robertmasen.pizza>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
bincode = "1.0.0"
wasm-bindgen = "=0.2.10"
wasm_tutorial_shared = {path = "../shared"}

[lib]
crate-type = ["cdylib"]