[package]
name = "wasm_tutorial_server"
version = "0.1.0"
authors = ["robert masen <r@robertmasen.pizza>"]

[dependencies]
hyper = "^0.11"
futures = "^0.1"
pony = "0"
wasm_tutorial_shared = { path = "../shared"}